# Generated by Django 4.2.16 on 2024-11-15 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_permissiongroup_employee_permission_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='permission_group',
        ),
        migrations.AddField(
            model_name='position',
            name='permission_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.permissiongroup'),
        ),
    ]
